name: awesome_project
description: A new Flutter project.
publish_to: 'none'

version: 1.0.2+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  mpflutter_core: ^2.7.5
  mpflutter_build_tools: ^2.7.6
  mpflutter_wechat_api: ^2.2.4
  mpflutter_wechat_mapview: ^0.0.3
  get: ^4.6.6
  audioplayers: ^5.2.0
  shared_preferences: ^2.2.2
  flashy_tab_bar2: ^0.0.10
  flutter_svg: ^2.0.10+1
  scrollable_list_tab_scroller: ^3.1.0
  uuid: ^4.3.3
  mpflutter_wechat_button: ^0.1.0


dependency_overrides:
  audioplayers_web:
    git:
      url: https://github.com/swiftdo/audioplayers.git
      ref: mpflutter-v5.2.1-inner
      path: packages/audioplayers_web


flutter:
  uses-material-design: true
  # 使用 MiniTex，不再需要加载任何字体，注释后，字体不会打包到小程序包中。
  # fonts:
  #   - family: Roboto
  #     fonts:
  #       - asset: fonts/Roboto-Regular.ttf
  #       - asset: fonts/Roboto-Bold.ttf
  #   - family: Noto Sans SC
  #     fonts:
  #       - asset: fonts/NotoSansSC-Regular.ttf
